-- Create and load the archive table for GRANTS_TO_DATABASE_ROLES CSV files.
-- Source path: @HAWK_AUDITLOGS_INTERNAL_STAGE/GRANTS_TO_DATABASE_ROLES/grants_to_database_roles_<YYYYMMDDHH24MISS>.csv
CREATE TABLE IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT.LOGS.GRANTS_TO_DATABASE_ROLES
  LIKE SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_DATABASE_ROLES;

COPY INTO ZSELECT_AUDITLOGS_STRICT.LOGS.GRANTS_TO_DATABASE_ROLES
FROM @HAWK_AUDITLOGS_INTERNAL_STAGE/GRANTS_TO_DATABASE_ROLES/
FILE_FORMAT = (FORMAT_NAME = ZSELECT_AUDITLOGS_STRICT.LOGS.AUDITLOGS_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*[.]csv'
ON_ERROR = ABORT_STATEMENT;
