-- Create and load the archive table for GRANTS_TO_USERS CSV files.
-- Source path: @HAWK_AUDITLOGS_INTERNAL_STAGE/GRANTS_TO_USERS/grants_to_users_<YYYYMMDDHH24MISS>.csv
CREATE TABLE IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT.LOGS.GRANTS_TO_USERS
  LIKE SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS;

COPY INTO ZSELECT_AUDITLOGS_STRICT.LOGS.GRANTS_TO_USERS
FROM @HAWK_AUDITLOGS_INTERNAL_STAGE/GRANTS_TO_USERS/
FILE_FORMAT = (FORMAT_NAME = ZSELECT_AUDITLOGS_STRICT.LOGS.AUDITLOGS_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*[.]csv'
ON_ERROR = ABORT_STATEMENT;
