-- Database, schema, and CSV file format for loading archived audit logs.
CREATE DATABASE IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT;

CREATE SCHEMA IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT.LOGS;

CREATE FILE FORMAT IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT.LOGS.AUDITLOGS_CSV_FORMAT
  TYPE = CSV
  PARSE_HEADER = TRUE
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  COMPRESSION = NONE
  NULL_IF = ('');
