-- Create and load the archive table for LOGIN_HISTORY CSV files.
-- Source path: @HAWK_AUDITLOGS_INTERNAL_STAGE/LOGIN_HISTORY/login_history_<YYYYMMDDHH24MISS>.csv
CREATE TABLE IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT.LOGS.LOGIN_HISTORY
  LIKE SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY;

COPY INTO ZSELECT_AUDITLOGS_STRICT.LOGS.LOGIN_HISTORY
FROM @HAWK_AUDITLOGS_INTERNAL_STAGE/LOGIN_HISTORY/
FILE_FORMAT = (FORMAT_NAME = ZSELECT_AUDITLOGS_STRICT.LOGS.AUDITLOGS_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*[.]csv'
ON_ERROR = ABORT_STATEMENT;
