-- Create and load the archive table for OBJECT_DEPENDENCIES CSV files.
-- Source path: @HAWK_AUDITLOGS_INTERNAL_STAGE/OBJECT_DEPENDENCIES/object_dependencies_<YYYYMMDDHH24MISS>.csv
CREATE TABLE IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT.LOGS.OBJECT_DEPENDENCIES
  LIKE SNOWFLAKE.ACCOUNT_USAGE.OBJECT_DEPENDENCIES;

COPY INTO ZSELECT_AUDITLOGS_STRICT.LOGS.OBJECT_DEPENDENCIES
FROM @HAWK_AUDITLOGS_INTERNAL_STAGE/OBJECT_DEPENDENCIES/
FILE_FORMAT = (FORMAT_NAME = ZSELECT_AUDITLOGS_STRICT.LOGS.AUDITLOGS_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*[.]csv'
ON_ERROR = ABORT_STATEMENT;
