-- Create and load the archive table for QUERY_HISTORY CSV files.
-- Source path: @HAWK_AUDITLOGS_INTERNAL_STAGE/QUERY_HISTORY/query_history_<YYYYMMDDHH24MISS>.csv
CREATE TABLE IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT.LOGS.QUERY_HISTORY
  LIKE SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY;

COPY INTO ZSELECT_AUDITLOGS_STRICT.LOGS.QUERY_HISTORY
FROM @HAWK_AUDITLOGS_INTERNAL_STAGE/QUERY_HISTORY/
FILE_FORMAT = (FORMAT_NAME = ZSELECT_AUDITLOGS_STRICT.LOGS.AUDITLOGS_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*[.]csv'
ON_ERROR = ABORT_STATEMENT;
