-- Create and load the archive table for SESSIONS CSV files.
-- Source path: @HAWK_AUDITLOGS_INTERNAL_STAGE/SESSIONS/sessions_<YYYYMMDDHH24MISS>.csv
CREATE TABLE IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT.LOGS.SESSIONS
  LIKE SNOWFLAKE.ACCOUNT_USAGE.SESSIONS;

COPY INTO ZSELECT_AUDITLOGS_STRICT.LOGS.SESSIONS
FROM @HAWK_AUDITLOGS_INTERNAL_STAGE/SESSIONS/
FILE_FORMAT = (FORMAT_NAME = ZSELECT_AUDITLOGS_STRICT.LOGS.AUDITLOGS_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*[.]csv'
ON_ERROR = ABORT_STATEMENT;
