-- Create and load the archive table for TAG_REFERENCES CSV files.
-- Source path: @HAWK_AUDITLOGS_INTERNAL_STAGE/TAG_REFERENCES/tag_references_<YYYYMMDDHH24MISS>.csv
CREATE TABLE IF NOT EXISTS ZSELECT_AUDITLOGS_STRICT.LOGS.TAG_REFERENCES
  LIKE SNOWFLAKE.ACCOUNT_USAGE.TAG_REFERENCES;

COPY INTO ZSELECT_AUDITLOGS_STRICT.LOGS.TAG_REFERENCES
FROM @HAWK_AUDITLOGS_INTERNAL_STAGE/TAG_REFERENCES/
FILE_FORMAT = (FORMAT_NAME = ZSELECT_AUDITLOGS_STRICT.LOGS.AUDITLOGS_CSV_FORMAT)
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*[.]csv'
ON_ERROR = ABORT_STATEMENT;
